/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.com.employee.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;employees&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.com.employee.model.impl.EmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.com.employee.model.impl.EmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @generated
 */
@ProviderType
public interface EmployeeModel extends BaseModel<Employee> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
	 */

	/**
	 * Returns the primary key of this employee.
	 *
	 * @return the primary key of this employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee.
	 *
	 * @param primaryKey the primary key of this employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee_id of this employee.
	 *
	 * @return the employee_id of this employee
	 */
	public long getEmployee_id();

	/**
	 * Sets the employee_id of this employee.
	 *
	 * @param employee_id the employee_id of this employee
	 */
	public void setEmployee_id(long employee_id);

	/**
	 * Returns the employee_name of this employee.
	 *
	 * @return the employee_name of this employee
	 */
	@AutoEscape
	public String getEmployee_name();

	/**
	 * Sets the employee_name of this employee.
	 *
	 * @param employee_name the employee_name of this employee
	 */
	public void setEmployee_name(String employee_name);

	/**
	 * Returns the employee_surname of this employee.
	 *
	 * @return the employee_surname of this employee
	 */
	@AutoEscape
	public String getEmployee_surname();

	/**
	 * Sets the employee_surname of this employee.
	 *
	 * @param employee_surname the employee_surname of this employee
	 */
	public void setEmployee_surname(String employee_surname);

	/**
	 * Returns the employee_department of this employee.
	 *
	 * @return the employee_department of this employee
	 */
	@AutoEscape
	public String getEmployee_department();

	/**
	 * Sets the employee_department of this employee.
	 *
	 * @param employee_department the employee_department of this employee
	 */
	public void setEmployee_department(String employee_department);

}